version: '3'

services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    restart: on-failure
