version: '3'

services:
  api:
    build:
      context: .
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    restart: on-failure

volumes:
  pgdata:
