version: '3'

services:
  pact:
    build:
      context: .
      dockerfile: ./Dockerfile.pact
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - pact-network
  db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - pactpgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    restart: on-failure
    networks:
      - pact-network

volumes:
  pactpgdata:

networks:
  pact-network:
    driver: bridge
