name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Spike
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          echo ${{ github.repository }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: overkilling/overkill-todo-infrastructure
          event-type: new_api_version
          client-payload: '{"repository": "${{ github.repository }}", "image_version": "$(echo sha-$(git rev-parse --short HEAD))"}'

  build-and-push-container:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: overkilling/overkill-todo-monolith-api/api
          tag_with_ref: true
          tag_with_sha: true
